version: 1.0.{build}

image: Visual Studio 2015

configuration: Release

# Configure both 32-bit and 64-bit builds
environment:
  matrix:
  - MSVC_PLATFORM: x86
  - MSVC_PLATFORM: x64

shallow_clone: true

build_script:
  - IF DEFINED MSVC_PLATFORM ".appveyor/msvc.bat"

artifacts:
  - path: graphene-shared-%MSVC_PLATFORM%.zip
    name: graphene-shared-%MSVC_PLATFORM%

test: off

# Upload .zip file to GitHub release
deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: "Graphene $(APPVEYOR_REPO_TAG_NAME)"
  provider: GitHub
  auth_token:
    secure: X7Ro8Y2RWYo/M1AAn93f9X0dEQFvu7gPb6li2eKRtzPYLGj/JKm7MNWRw2cCcjm6
  artifact: graphene-shared-$(MSVC_PLATFORM)
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true # deploy on tag push only
