version: 1.0.{build}

image: Visual Studio 2015

configuration: Release

# Configure both 32-bit and 64-bit builds for MSVC / MSYS2
environment:
  matrix:
    - MSVC_PLATFORM: x86
      DO_DEPLOY: true
    - MSVC_PLATFORM: x64
      DO_DEPLOY: true
    - MSYSTEM: MINGW64
    - MSYSTEM: MINGW32

# AppVeyor doesn't do this automatically like Travis does
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

build_script:
  - IF DEFINED MSVC_PLATFORM ".appveyor/msvc.bat"
  - IF DEFINED MSYSTEM set CHERE_INVOKING=yes
  - IF DEFINED MSYSTEM C:\msys64\usr\bin\bash -lc "bash -x .appveyor/msys2-pre.sh"
  - IF DEFINED MSYSTEM C:\msys64\usr\bin\bash -lc "bash -x .appveyor/msys2.sh"

artifacts:
  - path: graphene-shared-%MSVC_PLATFORM%.zip
    name: graphene-shared-%MSVC_PLATFORM%

test: off

# Upload .zip file to GitHub release
deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: "Graphene $(APPVEYOR_REPO_TAG_NAME)"
  provider: GitHub
  auth_token:
    secure: X7Ro8Y2RWYo/M1AAn93f9X0dEQFvu7gPb6li2eKRtzPYLGj/JKm7MNWRw2cCcjm6
  artifact: graphene-shared-$(MSVC_PLATFORM)
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true # deploy on tag push only
    DO_DEPLOY: true
